# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2d28087b5c0ecc3a51ac2089905206e"
name = "cart-snapshot-app"
handle = "cart-snapshot-app"
application_url = "https://planner-arrives-lanka-thinking.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cart-snapshot.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://planner-arrives-lanka-thinking.trycloudflare.com/auth/callback",
  "https://planner-arrives-lanka-thinking.trycloudflare.com/auth/shopify/callback",
  "https://planner-arrives-lanka-thinking.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
